<?xml version='1.0'?>

<!-- TODO: Switch back to 4 wheel skid steer drive -->

<robot name="atom" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="height_offset" value="0.0002" /> <!-- How far the robot starts off the ground -->
	<xacro:property name="front_offset" value="0.3" /> <!-- How far forward the wheels and lidar are compared to the center of the chassis -->
	<xacro:property name="back_offset" value="-0.5715" /> <!-- How far back the caster wheel is compared to the center of the chassis -->
	
	<xacro:property name="chassis_mass" value="29.9371" />
	<xacro:property name="chassis_length" value="1.143" />
	<xacro:property name="chassis_width" value="0.6096" />
	<xacro:property name="chassis_height" value="0.5588" />

	<xacro:property name="caster_radius" value="0.05" />

	<xacro:property name="wheel_mass" value="5" />
	<xacro:property name="wheel_radius" value="0.157226" />
	<xacro:property name="wheel_width" value="0.1" />
	<xacro:property name="wheel_separation" value="0.72" /> <!-- Distance from center to center -->

	<xacro:property name="camera_mass" value="0.1"/>
	<xacro:property name="camera_front_offset" value="0.5715"/> <!-- How far forward the camera is compared to the center of the chassis -->
	<xacro:property name="camera_z_offset" value="-0.2"/> <!-- How far down the camera is compared to the center of the chassis -->

	<xacro:property name="lidar_height" value="0.89535"/> <!-- The distance from the base of the chassis to the base of the LiDAR -->

	<!-- Robot footprint on ground -->
	<link name="robot_footprint" />

	<!-- Chassis -->
	<link name="chassis">
		<pose>0.536448 -0.130302 0.066802 0 0 0</pose>

		<inertial>
			<mass value="${chassis_mass}" />
			<origin xyz="0 0 0" rpy="0 0 0" />

			<inertia
				ixx="1.699" ixy="0" ixz="0"
				iyy="4.022" iyz="0"
				izz="4.170"
			/>
		</inertial>

		<collision name="collision">
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
			</geometry>
		</collision>

		<visual name="chassis_visual">
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_length} ${chassis_width} ${chassis_height}" />
			</geometry>

		</visual>

		<collision name='caster_collision'>
			<origin xyz="${back_offset} 0 ${-chassis_height/2-wheel_radius+caster_radius}" rpy=" 0 0 0"/>
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
			<surface>
				<friction>
				<ode>
					<mu>1</mu>
					<mu2>1</mu2>
					<slip1>0.5</slip1>
					<slip2>0</slip2>
				</ode>
				</friction>
			</surface>
		</collision>
	  
		<visual name='caster_visual'>
			<origin xyz="${back_offset} 0 ${-chassis_height/2-wheel_radius+caster_radius}" rpy=" 0 0 0"/>
			<geometry>
				<sphere radius="${caster_radius}"/>
			</geometry>
		</visual>
	</link>

	<!-- Wheels -->
	<xacro:include filename="$(find atom)/urdf/wheel.xacro"/>
	<xacro:wheel prefix="right" mass="${wheel_mass}" radius="${wheel_radius}" width="${wheel_width}">
		<origin xyz="${front_offset} -${wheel_separation/2} ${-chassis_height/2}" rpy="0 0 0" />
	</xacro:wheel>
	<xacro:wheel prefix="left" mass="${wheel_mass}" radius="${wheel_radius}" width="${wheel_width}">
		<origin xyz="${front_offset} ${wheel_separation/2} ${-chassis_height/2}" rpy="0 0 0" />
	</xacro:wheel>

	<!-- Camera -->
	<xacro:include filename="$(find atom)/urdf/camera.xacro"/>
	<xacro:camera mass="${camera_mass}">
		<origin xyz="${camera_front_offset} 0 ${camera_z_offset}" rpy="0 0 0" />
	</xacro:camera>

	<!-- LiDAR -->
	<xacro:include filename="$(find velodyne_description)/urdf/VLP-16.urdf.xacro" />
	<xacro:VLP-16 parent="chassis" name="velodyne" topic="/points2" hz="10" samples="250" gpu="false">
		<origin xyz="${front_offset} 0 ${-chassis_height/2+lidar_height}" rpy="0 0 0" />
	</xacro:VLP-16>

	<!-- IMU -->
	<link name="imu_link" />

	<!-- IMU Joint -->
	<joint name="imu_joint" type="fixed">
		<origin xyz="0 0 0" rpy="0 0 0" />
		<parent link="chassis" />
		<child link="imu_link" />
		<axis xyz="0 1 0" />
	</joint>

	<!-- Chassis Joint -->
	<joint name="robot_footprint_joint" type="fixed">
		<origin xyz="0 0 ${chassis_height/2+wheel_radius+height_offset}" rpy="0 0 0" />
		<parent link="robot_footprint" />
		<child link="chassis" />
	</joint>

	<!-- Color of bot -->
	<gazebo reference="chassis">
		<material>Gazebo/Blue</material>
	</gazebo>

	<!-- Motor, Camera and IMU Simulation -->
	<xacro:include filename="$(find atom)/urdf/atom.gazebo" />
</robot>